/**
 * @file sub-process.c
 *
 * Utility to launch a sub-processes and interact with them.
 * (Windows native version)
 *
 * The initial version was 98% generated by Gemni 3.1 Pro from the
 * linux version. Once we spin the wheels on this, it still needs a
 * few style fixes to match our coding conventions.
 */

/**
 * @enum sub_process_exit_status_t
 */
typedef enum {
  EXIT_STATUS_UNKNOWN,
  EXIT_STATUS_NORMAL_EXIT,
  EXIT_STATUS_SIGNAL,
  EXIT_STATUS_ABNORMAL
} sub_process_exit_status_t;

typedef struct {
  // launch parameters
  value_array_t* argv; // argv[0] is the program executable path (after env vars)

  // child process information
  HANDLE hProcess;
  HANDLE hThread;
  DWORD pid;
  HANDLE stdin_handle;
  HANDLE stdout_handle;
  HANDLE stderr_handle;

  // exit info
  sub_process_exit_status_t exit_status;
  int exit_code;
  int exit_signal;
} sub_process_t;

/**
 * @function make_sub_process
 *
 * Make and return an *unlaunched* sub-process.
 */
sub_process_t* make_sub_process(value_array_t* argv) {
  sub_process_t* result = malloc_struct(sub_process_t);
  result->argv = argv;
  result->exit_code = -1;
  result->hProcess = NULL;
  result->hThread = NULL;
  result->stdin_handle = NULL;
  result->stdout_handle = NULL;
  result->stderr_handle = NULL;
  result->exit_status = EXIT_STATUS_UNKNOWN;
  return result;
}

/**
 * @function sub_process_launch
 *
 * Do the actual sub process launch using the "arguments" in
 * sub_process_t.
 */
boolean_t sub_process_launch(sub_process_t* sub_process) {
  uint64_t length = sub_process->argv->length;
  if (length < 1) {
    log_fatal("Expected at least the program path in argv");
    fatal_error(ERROR_ILLEGAL_STATE);
  }

  // 1. Setup pipe security attributes so child inherits handles
  SECURITY_ATTRIBUTES saAttr = {0};
  saAttr.nLength = sizeof(SECURITY_ATTRIBUTES);
  saAttr.bInheritHandle = TRUE;
  saAttr.lpSecurityDescriptor = NULL;

  HANDLE hChildStd_IN_Rd = NULL;
  HANDLE hChildStd_IN_Wr = NULL;
  HANDLE hChildStd_OUT_Rd = NULL;
  HANDLE hChildStd_OUT_Wr = NULL;
  HANDLE hChildStd_ERR_Rd = NULL;
  HANDLE hChildStd_ERR_Wr = NULL;

  // 2. Create pipes for stdin, stdout, and stderr
  if (!CreatePipe(&hChildStd_OUT_Rd, &hChildStd_OUT_Wr, &saAttr, 0) ||
      !CreatePipe(&hChildStd_ERR_Rd, &hChildStd_ERR_Wr, &saAttr, 0) ||
      !CreatePipe(&hChildStd_IN_Rd, &hChildStd_IN_Wr, &saAttr, 0)) {
    log_fatal("Failed to create pipes for stdin, stdout or stderr");
    fatal_error(ERROR_ILLEGAL_STATE);
    return false;
  }

  // Ensure the read handles to the pipes for STDOUT and STDERR are not inherited.
  // Ensure the write handle to the pipe for STDIN is not inherited.
  SetHandleInformation(hChildStd_OUT_Rd, HANDLE_FLAG_INHERIT, 0);
  SetHandleInformation(hChildStd_ERR_Rd, HANDLE_FLAG_INHERIT, 0);
  SetHandleInformation(hChildStd_IN_Wr, HANDLE_FLAG_INHERIT, 0);

  // 3. Process environment variables off the front of argv
  int offset = 0;
  while (offset < length) {
    char* env_str = value_array_get_ptr(sub_process->argv, offset, typeof(char*));
    if (strchr(env_str, '=') == NULL) {
        break; // Reached the actual executable
    }

    // TODO(jawilson): this is gross!
    char* equals = strchr(env_str, '=');
    if (*(equals + 1) == '\0') {
      *equals = '\0';
      SetEnvironmentVariableA(env_str, NULL); // e.g., "FOO=" unsets FOO
    } else {
      *equals = '\0';
      SetEnvironmentVariableA(env_str, equals + 1); // e.g., "FOO=bar" sets FOO
      *equals = '='; // restore string
    }
    offset++;
  }

  if (offset >= length) {
    log_fatal("No executable specified after environment variables");
    fatal_error(ERROR_ILLEGAL_STATE);
  }

  // 4. Build a single command line string for Windows CreateProcess
  // Windows requires a single flat string, unlike execvp's array.
  size_t cmd_len = 0;
  for (int i = offset; i < length; i++) {
      char* arg = value_array_get_ptr(sub_process->argv, i, typeof(char*));
      cmd_len += strlen(arg) + 3; // +3 for quotes and space
  }

  char* cmd_line = cast(typeof(char*), malloc_bytes(cmd_len + 1));
  cmd_line[0] = '\0';
  for (int i = offset; i < length; i++) {
      char* arg = value_array_get_ptr(sub_process->argv, i, typeof(char*));
      strcat(cmd_line, "\"");
      strcat(cmd_line, arg);
      strcat(cmd_line, "\" ");
  }

  // 5. Setup STARTUPINFO and PROCESS_INFORMATION
  STARTUPINFOA si = {0};
  // TODO(jawilson): do we still need this?
  ZeroMemory(&si, sizeof(STARTUPINFOA));
  si.cb = sizeof(STARTUPINFOA);
  si.hStdError = hChildStd_ERR_Wr;
  si.hStdOutput = hChildStd_OUT_Wr;
  si.hStdInput = hChildStd_IN_Rd;
  si.dwFlags |= STARTF_USESTDHANDLES;

  PROCESS_INFORMATION pi = {0};
  ZeroMemory(&pi, sizeof(PROCESS_INFORMATION));

  char* executable = value_array_get_ptr(sub_process->argv, offset, typeof(char*));

  // 6. Launch the process
  BOOL success = CreateProcessA(
      NULL,           // Application name (can be null if passed in cmd line)
      cmd_line,       // Command line
      NULL,           // Process security attributes
      NULL,           // Primary thread security attributes
      TRUE,           // Handles are inherited
      0,              // Creation flags
      NULL,           // Use parent's environment block
      NULL,           // Use parent's starting directory 
      &si,            // Pointer to STARTUPINFO pointer
      &pi             // Pointer to PROCESS_INFORMATION
  );

  if (!success) {
    log_fatal("CreateProcessA failed (%d).", GetLastError());
    fatal_error(ERROR_ILLEGAL_STATE);
    return false;
  }

  // 7. Close child-side pipe handles in the parent so we don't leak them
  // and so reads/writes can return EOF when the child exits.
  CloseHandle(hChildStd_OUT_Wr);
  CloseHandle(hChildStd_ERR_Wr);
  CloseHandle(hChildStd_IN_Rd);

  // 8. Record process and handle info
  sub_process->hProcess = pi.hProcess;
  sub_process->hThread = pi.hThread;
  sub_process->pid = pi.dwProcessId;
  sub_process->stdin_handle = hChildStd_IN_Wr;
  sub_process->stdout_handle = hChildStd_OUT_Rd;
  sub_process->stderr_handle = hChildStd_ERR_Rd;

  return true;
}

uint64_t sub_process_write(sub_process_t* sub_process, buffer_t* data,
                           uint64_t start_position) {
  HANDLE stdin_handle = sub_process->stdin_handle;
  if (stdin_handle == NULL) return 0;

  DWORD bytes_written = 0;
  DWORD bytes_to_write = (DWORD)(data->length - start_position);
  
  // Note: Standard anonymous pipes in Windows are blocking.
  // To avoid deadlock, ensure buffer sizes don't exceed pipe capacity (typically 4KB)
  // or use threads/overlapped I/O with named pipes.
  BOOL success = WriteFile(stdin_handle, 
                           &data->elements[start_position], 
                           bytes_to_write, 
                           &bytes_written, 
                           NULL);

  if (!success) {
    DWORD error = GetLastError();
    if (error == ERROR_BROKEN_PIPE) {
      // Child closed its stdin
      return 0;
    } else {
      log_fatal("Error writing to subprocess stdin: %d", error);
      fatal_error(ERROR_ILLEGAL_STATE);
    }
  }

  return bytes_written;
}

void sub_process_close_stdin(sub_process_t* sub_process) {
  if (sub_process->stdin_handle != NULL) { 
    if (!CloseHandle(sub_process->stdin_handle)) {
      log_fatal("Error closing subprocess stdin: %d", GetLastError());
      fatal_error(ERROR_ILLEGAL_STATE);
    }
    sub_process->stdin_handle = NULL;
  }
}

void sub_process_read(sub_process_t* sub_process, buffer_t* stdout_buffer,
                      buffer_t* stderr_buffer) {
  // Assuming a Windows equivalent for buffer_read_ready_bytes exists in your codebase.
  // E.g., `buffer_read_ready_bytes_handle(buffer, handle, max_bytes)`
  // This typically uses PeekNamedPipe to check for available bytes, then ReadFile.
  if (stdout_buffer != NULL && sub_process->stdout_handle != NULL) {
    buffer_read_ready_bytes_handle(stdout_buffer, sub_process->stdout_handle, 0xffffffff);
  }
  if (stderr_buffer != NULL && sub_process->stderr_handle != NULL) {
    buffer_read_ready_bytes_handle(stderr_buffer, sub_process->stderr_handle, 0xffffffff);
  }
}

// (Private) common tail to is_sub_process_running and
// sub_process_wait. This should only be called once per sub-process.
void sub_process_record_exit_status(sub_process_t* sub_process, DWORD exit_code) {
  // Windows doesn't distinguish deeply between exits and signals in the same way 
  // POSIX does (e.g. WIFSIGNALED), but unhandled exceptions often return 
  // large NTSTATUS codes (e.g., 0xC0000005 for Access Violation).
  
  sub_process->exit_code = exit_code;
  
  if (exit_code >= 0xC0000000) { 
    sub_process->exit_status = EXIT_STATUS_ABNORMAL;
  } else {
    sub_process->exit_status = EXIT_STATUS_NORMAL_EXIT;
  }

  // Clean up handles
  if (sub_process->hProcess) CloseHandle(sub_process->hProcess);
  if (sub_process->hThread) CloseHandle(sub_process->hThread);
  if (sub_process->stdout_handle) CloseHandle(sub_process->stdout_handle);
  if (sub_process->stderr_handle) CloseHandle(sub_process->stderr_handle);
  
  sub_process->hProcess = NULL;
  sub_process->hThread = NULL;
  sub_process->stdout_handle = NULL;
  sub_process->stderr_handle = NULL;
}

/**
 * @function is_sub_process_running
 *
 * Return true if we recorded that the process already exited or else
 * do a non-blocking call to WaitForSingleObject to see if it has already
 * exited. This function is idempotent once we reach the exit state.
 */
boolean_t is_sub_process_running(sub_process_t* sub_process) {
  if (sub_process->exit_status != EXIT_STATUS_UNKNOWN) {
    return false;
  }

  DWORD wait_result = WaitForSingleObject(sub_process->hProcess, 0); // 0 timeout = non-blocking
  if (wait_result == WAIT_TIMEOUT) {
    return true;
  }

  DWORD exit_code = 0;
  if (wait_result == WAIT_OBJECT_0) {
      GetExitCodeProcess(sub_process->hProcess, &exit_code);
  } else {
      exit_code = (DWORD)-1; // Abnormal / failure to wait
  }

  sub_process_record_exit_status(sub_process, exit_code);
  return false;
}

/**
 * @function sub_process_wait
 *
 * Do a blocking call to WaitForSingleObject unless we've already recorded that
 * this sub-process has exited in which case it is a NOP. This
 * function is idempotent once we reach the exit state.
 */
void sub_process_wait(sub_process_t* sub_process) {
  if (sub_process->exit_status == EXIT_STATUS_UNKNOWN) {
    WaitForSingleObject(sub_process->hProcess, INFINITE);
    
    DWORD exit_code = 0;
    GetExitCodeProcess(sub_process->hProcess, &exit_code);
    sub_process_record_exit_status(sub_process, exit_code);
  }
}

/**
 * @function sub_process_launch_and_wait
 */
void sub_process_launch_and_wait(sub_process_t* sub_process,
                                 buffer_t* child_stdin, buffer_t* child_stdout,
                                 buffer_t* child_stderr) {
  sub_process_launch(sub_process);
  uint64_t written = 0;
  do {
    if (child_stdin != NULL && written < child_stdin->length) {
      written += sub_process_write(sub_process, child_stdin, written);
      if (written >= child_stdin->length) {
        sub_process_close_stdin(sub_process);
      }
    }
    sub_process_read(sub_process, child_stdout, child_stderr);
    Sleep(5); // Replaced usleep(5) -> Sleep(5ms). Sleep(0) or Sleep(1) also work to yield execution.
  } while (is_sub_process_running(sub_process));
  
  sub_process_read(sub_process, child_stdout, child_stderr);
  sub_process_wait(sub_process);
}
